name: monitoring
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  firebase_dynamic_links: ^6.0.10
  firebase_analytics: ^11.3.5
  firebase_remote_config: ^5.1.5

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8